### ISSUE TITLE
# LF/ProofObjects

### ISSUE THREAD

**Issue by exprosic** [Rocq-zh/SF-zh#8]
> We have seen that Coq has mechanisms both for programming, using inductive data types like nat or list and functions over these types, and for proving properties of these programs, using inductive propositions (like ev), implication, universal quantification, and the like. So far, we have mostly treated these mechanisms as if they were quite separate, and for many purposes this is a good way to think. 

\- 我们已经知道Coq的机制有两种不同的目的。一种是为了**编程**， 使用归纳数据类型如 nat 和 list，以及在这些类型上的函数；另一种是为了**证明**程序的性质，使用归纳命题（如 ev），蕴含式，全称量化等等。目前为止，我们一直认为这些机制是相当不同的。有些时候，这也确实 是比较好的思考方式。

\+ 我们已经知道Coq可以做两件事：一是**编程**，用的是归纳数据类型如 nat 和 list 及相关函数；二是**证明**程序的性质，用的是归纳命题（如 ev）、蕴含式、全称量化等等。目前为止，我们一直把这两者用到的方法完全区分看待，当然很多时候这样看待并没有错。

// “机制”相比“mechanism”太过具体，导致“Coq的机制”语焉不详。这里用has mechanisms for只是英文习惯，此处的语义基本等价与has tools for，约等于has ability to。

**Comment by exprosic** [comment]
> But we have also seen hints that Coq's programming and proving facilities are closely related. 

\- 但是我们也看到过一些暗示，表明Coq的编程和证明 的各种工具是非常相关的。
\+ 但是我们也看到过一些迹象，表明Coq用来编程和证明的方法是紧密相关的。

**Comment by exprosic** [comment]
> When we construct the proof of a basic proposition, we are actually building a tree of evidence, which can be thought of as a data structure.

\-  当我们为一个基本的命题构造证明的时候，我们实际上是在构造证 据树。证据树可被认为是一种数据结构。
\+  当我们为一个基本的命题构造证明的时候，我们实际上是在构造一棵证据树。你可以把它当成一种数据结构。

// “a tree of evidence”而非“Evidence Tree”，直言“证据树”可能被误以为是专有名词。
// “which can be thought of as a data structure”原文中只是语气极轻的注解，直译为“可被认为”可能会被误以为是另起一条重要信息。

**Comment by exprosic** [comment]
> If the proposition is an implication like A → B, then its proof will be an evidence *transformer*: a recipe for converting evidence for A into evidence for B. 

\- 如果这个命题是一个蕴含式，像是 A → B，那么它的证明是一个证据 的**转换器 (Transformer)**：一个将 A 的证据转换为 B 的证据的配方。

\+ 比如对于形如“A → B”的蕴含式来说，它的证明就是一个证据“转换器”，包含了将 A 的证据转换为 B 的证据的具体过程。

// “这个命题”在中文里指代不明，原文“if the”仅用于举例。
// “transformer”不是专有名词，更不是大写加粗专有名词。原文加斜体仅表明形象比喻。

**Comment by exprosic** [comment]
> Question: If evidence is data, what are propositions themselves?
> Answer: They are types!

\- 问题：如果是证据是数据，那么命题本身是什么？
\- 答案：它们是类型！

\+ 如果是命题的证据是数据，那么命题本身是什么？
\+ 是类型！

// 看不懂的幽默最为尴尬。。。

**Comment by exprosic** [comment]
> Suppose we introduce an alternative pronunciation of ":". Instead of "has type," we can say "is a proof of." For example, the second line in the definition of ev declares that ev_0 : ev 0. Instead of "ev_0 has type ev 0," we can say that "ev_0 is a proof of ev 0."

\- 假设我们引入 “:” 的另外一种阅读方式。我们不说“……的类型是……”， 而说“……是……的证明”。例如，ev 定义的第二行声明了 ev_0 : ev 0。 我们不说“ev_0 拥有类型 ev 0”，而说“ev_0 是 ev 0 的证明”。

\+ 假设我们换一种方式解读 “:”，我们不说“……的类型是……”， 而说“……是……的证明”。例如，这里第二行说 ev_0 : ev 0，我们可以不把它读成“ev_0 拥有类型 ev 0”，而读成“ev_0 是 ev 0 的证明”。

// “:”本身不需要阅读，也不需要pronounce。原文用“pronunciation”来表示一种浅层的看待方式，如果找不到合适的直译方式，不如在前半句先明确“看待方式”（解读），而在后边句中暗示“浅层的看待方式”（读成...）。

**Comment by exprosic** [comment]
> This pun between types and propositions — between : as "has type" and : as "is a proof of" or "is evidence for" — is called the Curry-Howard correspondence. It proposes a deep connection between the world of logic and the world of computation:

\- 这个类型和命题之间的双关语，或者说，: 的两种阅读方式“……的类型是……” 和“……是……的证明”之间的双关语，称为 柯里-霍华德对应 (Curry-Howard correspondence)。 它提出了逻辑世界和计算世界之间深层次的关联：

\+ 这种类型和命题之间的双关现象，或者说上文里“:”同时可以读作“类型是”和“证明了”的现象，叫作 **柯里-霍华德对应 (Curry-Howard correspondence)**。它提出了逻辑和计算两个领域之间深层次的关联：

**Comment by OlingCat** [comment]
@exprosic 乃要加入翻译项目组么0.0？

**Comment by exprosic** [comment]
> Many useful insights follow from this connection. To begin with, it gives us a natural interpretation of the type of the ev_SS constructor:

\- 很多有用的简介都来自这一关联。首先，它赋予了 ev_SS 这个构造器的 类型的一个自然的理解：

\+ 这个关联提供了一个看透问题的视角。首先，我们可以用它自然地解读 ev_SS 这个构造器：

**Comment by exprosic** [comment]
> This can be read "ev_SS is a constructor that takes two arguments — a number n and evidence for the proposition ev n — and yields evidence for the proposition ev (S (S n))."

\- 这可以读为“ev_SS是一个构造器，接受两个参数——一个数字 n 和一 个命题 ev n的证据——然后产生一个命题 ev (S (S n)) 的证据。”

\+ 这可以读作“ev_SS这个构造器接受两个参数：数字 n 和命题 ev n 的证据，然后构造出命题 ev (S (S n)) 的证据。”

**Comment by exprosic** [comment]
> Indeed, we can also write down this proof object directly, without the need for a separate proof script:

\- 实际上，我们也可以**直接（directly）**写出证明对象本身，不需要一个单独的证明脚本。
\+ 实际上，我们也可以直接写出证明对象，而不需要通过另写证明脚本来构造：

// 语气词不是专有名词

**Comment by exprosic** [comment]
> The expression ev_SS 2 (ev_SS 0 ev_0) can be thought of as instantiating the parameterized constructor ev_SS with the specific arguments 2 and 0 plus the corresponding proof objects for its premises ev 2 and ev 0. 

\- 表达式 ev_SS 2 (ev_SS 0 ev_0) 可以被认为是将参数化的构造器 ev_SS 使用具体的参数 2， 0，以及它们对应的证明对象 ev 2 和 ev 0 给实例化了。 

\+ 表达式 ev_SS 2 (ev_SS 0 ev_0) 可以看作是先往构造器 ev_SS 中带入具体的参数 2 和 0，再补充作为证明前提的 ev 2 和 ev 0 的证明对象。

// 首先，ev 2 和 ev 0 是命题，不是证明对象
// 其次，“corresponding” 这里指的不是 ev 2/ev 0 和参数 2/0的对应，而是命题 ev 2/ev0 和它们的proof object之间的对应。
// 再次，“实例化”容易被放入面向对象程序设计的语境下解读，而 instantiate 这里指数学意义上的参数代入。

**Comment by exprosic** [comment]
> Alternatively, we can think of ev_SS as a primitive "evidence constructor" that, when applied to a particular number, wants to be further applied to evidence that that number is even; its type,

\- 或者，我们可以将 ev_SS 认为是一个原子的“对 象构造器”，当被应用到一个具体的数字时，它要求给出这个数字是偶数的 证据。

\+ 或者，我们可以将 ev_SS 看作一个底层的“证据构造器”，它除了需要一个具体的数字时，还要求给出这个数字是偶数的证据。

**Comment by exprosic** [comment]
>  its type, \\ ∀ n, ev n → ev (S (S n)), \\ expresses this functionality,

\- 这个功能可以通过它的类型 [ ∀n, ev n → ev (S (S n)), ] 看出
\+ 这可以通过它的类型看出：(*用来保持排版的换行*) ∀n, ev n → ev (S (S n))  (*这里没有逗号*)

// 用“this functionality”仅仅因为用“this”头重脚轻，而“functionality”本身仅泛指上文所述，并不指代什么具体“功能”。

**Comment by exprosic** [comment]
> in the same way that the polymorphic type ∀X, list X expresses the fact that the constructor nil can be thought of as a function from types to empty lists with elements of that type.

\- 类似的例子有，多态类型 ∀X, list X 表明了构造器 nil 可以被认为 是一个从类型到该类型的空列表的函数。
\+ 这就好比构造器 nil 的多态类型 ∀X, list X 表明了它可以被看成一个从某类型到元素为该类型的空列表的函数。

// 不明说 nil 和 ∀X, list X 的关系放在英文里感觉是修辞，放在翻译腔中文里就是搬石头砸脚的阅读障碍。

**Comment by exprosic** [comment]
> @exprosic 乃要加入翻译项目组么0.0？

吼啊:)

**Comment by liyishuai** [comment]
> // “a tree of evidence”而非“Evidence Tree”，直言“证据树”可能被误以为是专有名词。

“证明树”（proof tree）可视为专有名词，指代“证明表达式（proof object）的语法树”。

**Comment by exprosic** [comment]
@liyishuai 证明树确实是专有名词，但“a tree of evidence”显然意在突出evidence与construct the proof的关系，而非引入专有名词“证明树”，因为一来证明树与curry-howard无直接关系，二来从行文上讲这里放专有名词缺乏上下文。

**Comment by liyishuai** [comment]
> @liyishuai 证明树确实是专有名词，但“a tree of evidence”显然意在突出evidence与construct the proof的关系，而非引入专有名词“证明树”，因为一来证明树与curry-howard无直接关系，二来从行文上讲这里放专有名词缺乏上下文。

“为基本命题构造证明，实则以树状结构表示其证据”何如？

**Comment by exprosic** [comment]
@liyishuai 只要允许这种尺度的翻译，那再好不过。

**Comment by liyishuai** [comment]
> > This can be read "ev_SS is a constructor that takes two arguments — a number n and evidence for the proposition ev n — and yields evidence for the proposition ev (S (S n))."
> 
> - 这可以读为“ev_SS是一个构造器，接受两个参数——一个数字 n 和一 个命题 ev n的证据——然后产生一个命题 ev (S (S n)) 的证据。”
> 
> + 这可以读作“ev_SS这个构造器接受两个参数：数字 n 和命题 ev n 的证据，然后**构造**出命题 ev (S (S n)) 的证据。”

**构造**还是**产生**？
狭义的**构造**指用**构造子**写证明的过程，但此处不在写证明而在声明构造子，故建议使用**产生**以示区分。

**Comment by liyishuai** [comment]
> > its type, \ ∀ n, ev n → ev (S (S n)), \ expresses this functionality,
> 
> - 这个功能可以通过它的类型 [ ∀n, ev n → ev (S (S n)), ] 看出
> + 这可以通过它的类型看出：(_用来保持排版的换行_) ∀n, ev n → ev (S (S n)) (_这里没有逗号_)
> 
> // 用“this functionality”仅仅因为用“this”头重脚轻，而“functionality”本身仅泛指上文所述，并不指代什么具体“功能”。

函数式编程中，常可依类型推断部分功能。当前语境下，类型即“功能”，故应保留。

**Comment by exprosic** [comment]
> > > This can be read "ev_SS is a constructor that takes two arguments — a number n and evidence for the proposition ev n — and yields evidence for the proposition ev (S (S n))."
> > 
> > 
> > 
> > * 这可以读为“ev_SS是一个构造器，接受两个参数——一个数字 n 和一 个命题 ev n的证据——然后产生一个命题 ev (S (S n)) 的证据。”
> > 
> > 
> > * 这可以读作“ev_SS这个构造器接受两个参数：数字 n 和命题 ev n 的证据，然后**构造**出命题 ev (S (S n)) 的证据。”
> 
> **构造**还是**产生**？
> 狭义的**构造**指用**构造子**写证明的过程，但此处不在写证明而在声明构造子，故建议使用**产生**以示区分。

没错，这里的问题不在于用的是否是构造子（显然是），而在于是描述类型（声明）还是在实际进行构造。我的理解是，这里正是在用描述实际构造（takes ... and yields ...）的方式来解释类型，而“接受……然后构造……”足以说明这是一个虚拟的过程描述，同时“构造”突出了这个过程正是“构造子”的功能。

**Comment by exprosic** [comment]
> > > its type, \ ∀ n, ev n → ev (S (S n)), \ expresses this functionality,
> > 
> > 
> > 
> > * 这个功能可以通过它的类型 [ ∀n, ev n → ev (S (S n)), ] 看出
> > 
> > 
> > * 这可以通过它的类型看出：(_用来保持排版的换行_) ∀n, ev n → ev (S (S n)) (_这里没有逗号_)
> > 
> > // 用“this functionality”仅仅因为用“this”头重脚轻，而“functionality”本身仅泛指上文所述，并不指代什么具体“功能”。
> 
> 函数式编程中，常可依类型推断部分功能。当前语境下，类型即“功能”，故应保留。

原文的“this functionality”指的是“... when applied to a particular number, wants to be further applied to evidence that that number is even”，而在中文语境中，“当被应用到一个具体的数字时，它要求给出这个数字是偶数的证据”并不是一般意义上的“功能”，它只是某种性质，而没有做任何事情。读者读到“功能”的时候必然会好奇这个“功能”在哪，是谁做了什么事。

**Comment by liyishuai** [comment]
@exprosic See Coq-zh/sfdev-zh#71
